FROM python:3.6-alpine
LABEL maintainer="Craig Derington <cderington@championsg.com>"
RUN apk update && apk upgrade
RUN apk add --no-cache --virtual build-deps build-base gcc python3-dev openssl-dev \
    libressl-dev libffi-dev screen curl
WORKDIR /code
COPY . /code
EXPOSE 5000
RUN pip3 install --no-cache-dir -r requirements-dev.txt
CMD ["flower", "-A", "celery_worker:celery", "--address=0.0.0.0", "--port=5000"]
